version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8090:3000"
    volumes:
      - .:/go/src/app
    depends_on:
      - postgres
    command: sh run.sh
  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_MAIN_PORT}
    volumes:
      - ./redis-data:/data