// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"github.com/google/wire"
	"golang/controllers/auth"
	auth2 "golang/interfaces/auth"
	"golang/interfaces/user"
	providers2 "golang/providers/auth"
	"golang/providers/user"
	user2 "golang/repositories/user"
	auth3 "golang/services/auth"
)

// Injectors from auth_wire.go:

func InitializeAuthController() *auth.AuthController {
	userRepository := providers.UserRepositoryProvider()
	authService := providers2.AuthServiceProvider(userRepository)
	authController := providers2.AuthControllerProvider(authService)
	return authController
}

// auth_wire.go:

var authProviderSet = wire.NewSet(providers2.AuthControllerProvider, providers2.AuthServiceProvider, wire.Bind(new(auth2.IAuthService), new(*auth3.AuthService)))

var userProviderSet = wire.NewSet(providers.UserRepositoryProvider, wire.Bind(new(user.IUserRepository), new(*user2.UserRepository)))
